site:
  author : jjeda
  features:
    auth : true
    

logging.level:
  todoapp: DEBUG
  org.springframework.boot: INFO
  org.springframework.web: DEBUG
    
    
spring:
  http:
    encoding:
      force: true